### ISSUE TITLE
编译失败求助。

### ISSUE THREAD

**Issue by wmjlxl** [douo/luci-app-tinyfecvpn#1]
大佬，

我用的 openwrt-sdk-19.07.2-x86-64_gcc-7.5.0_musl.Linux-x86_64 来编译。

最后发现失败了，具体信息如下，请问哪里可以修正呢？ 谢谢。

-----

WARNING: Makefile 'package/linux/Makefile' has a dependency on 'r8169-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'e100-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'bnx2-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'ar3k-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'mwifiex-sdio-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb2', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'edgeport-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb3', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'amdgpu-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'radeon-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'prism54-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'rtl8192su-firmware', which does not exist
tmp/.config-package.in:36:warning: ignoring type redefinition of 'PACKAGE_libc' from 'boolean' to 'tristate'
tmp/.config-package.in:64:warning: ignoring type redefinition of 'PACKAGE_libgcc' from 'boolean' to 'tristate'
tmp/.config-package.in:149:warning: ignoring type redefinition of 'PACKAGE_libpthread' from 'boolean' to 'tristate'
tmp/.config-package.in:177:warning: ignoring type redefinition of 'PACKAGE_librt' from 'boolean' to 'tristate'
#
# configuration written to .config
#
make[1]: Entering directory `/home/will/openwrt-sdk'
make[2]: Entering directory `/home/will/openwrt-sdk/package/toolchain'
Makefile:630: WARNING: skipping libgomp -- package has no install section
rm -rf /home/will/openwrt-sdk/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed /home/will/openwrt-sdk/build_dir/target-x86_64_musl/toolchain/
.pkgdir/libc
mkdir -p /home/will/openwrt-sdk/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc
install -d -m0755 /home/will/openwrt-sdk/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/lib /home/will/openwrt-sdk/build_dir/target-x86_64_musl/toolc
hain/.pkgdir/libc/usr/bin
cp -fpR /home/will/openwrt-sdk/staging_dir/toolchain-x86_64_gcc-7.5.0_musl/lib/ld-musl-*.so* /home/will/openwrt-sdk/build_dir/target-x86_64_musl/toolchain
/.pkgdir/libc/lib/
cp: cannot stat '/home/will/openwrt-sdk/staging_dir/toolchain-x86_64_gcc-7.5.0_musl/lib/ld-musl-*.so*': No such file or directory
make[2]: *** [/home/will/openwrt-sdk/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed] Error 1
make[2]: Leaving directory `/home/will/openwrt-sdk/package/toolchain'
time: package/toolchain/compile#0.01#0.00#0.11
make[1]: *** [package/toolchain/compile] Error 2
make[1]: Leaving directory `/home/will/openwrt-sdk'
make: *** [package/luci-app-tinyfecvpn/compile] Error 2

**Comment by douo** [comment]
抱歉哈，编译还没测试过，不过这个插件没有依赖，所谓编译，实际上就是复制粘贴而已。先确保你的 openwrt 能编译通过，再加这个插件重新编译下看看。

也可以编译好系统后，手动操作：参考这个： https://github.com/douo/luci-app-tinyfecvpn/blob/master/Makefile#L56

**Comment by douo** [comment]
已修复
